[package]
name = "mandara-formats"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mandara-core = { path = "../mandara-core" }
encoding_rs = { workspace = true }
epub = { workspace = true }
scraper = { workspace = true }
uuid = { workspace = true }
ego-tree = "0.11"
url = { workspace = true }
percent-encoding = "2.3"
roxmltree = "0.21"
cssparser = "0.37"
base64 = "0.22"
serde_json = { workspace = true }

zip = { workspace = true }