/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health and capabilities */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in, receive a JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user (Authorization header or session cookie)
         * @description The authenticated user. Accepts the JWT via `Authorization:
         *     Bearer …` or via the `mandara_token` session cookie (set on
         *     register/login) — the cookie keeps the login alive across page
         *     refreshes.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie (stateless JWT: nothing else to invalidate) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered plugin instances (id, wasm file, name, capabilities) */
        get: operations["listPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/wasm-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Basenames of the compiled wasm components loaded at startup (admin only) */
        get: operations["wasmFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-sync the catalogs of every enabled declare-capable instance (admin only) */
        post: operations["syncPlugins"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a plugin instance (admin only). `wasm_file` must be a
         *     basename returned by GET /api/plugins/wasm-files; `config` is
         *     validated against the plugin's config schema (defaults fill the
         *     rest). An explicit `id` becomes the source id used in
         *     `book_files.source` — stable ids let metadata plugins point their
         *     `content-source` at a content plugin's instance. A declare-capable
         *     instance is synced right away.
         */
        post: operations["registerInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a plugin instance (admin only) */
        delete: operations["deleteInstance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances/{id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Enable or disable a plugin instance (admin only). Disabling stops
         *     sync/browse/materialize; already materialized chapters stay
         *     readable.
         */
        put: operations["setInstanceEnabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-catalogue one plugin instance (admin only)
         * @description Re-sync the declared catalog of a single instance into the library
         *     (the per-instance 重同步 button in the admin page; the full sync
         *     is POST /api/plugins/sync).
         */
        post: operations["syncInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/config-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config schema plus current values for the admin form (admin only) */
        get: operations["pluginConfigSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Validate and store an instance's configuration (admin only).
         *     Unknown keys are rejected, required fields enforced, enum indices
         *     range-checked; errors come back field-by-field for inline form
         *     display. A declare-capable instance is re-synced after the change.
         */
        put: operations["putPluginConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated catalog search of a search-capable instance. The library
         *     does not enumerate large sources; users pick books here and add
         *     them through the unified acquisition endpoint (POST /api/books
         *     with plugin_source + plugin_book_id). Caps: limit 1..50,
         *     offset <= 10000.
         */
        get: operations["searchPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible books with their visible files */
        get: operations["listBooks"];
        put?: never;
        /**
         * Add a book to the library — the single acquisition flow
         *     (获取书籍 → 添加元数据). The content is either an uploaded
         *     `file`, a plugin book (`plugin_source` + `plugin_book_id`
         *     without a `file`; the plugin supplies the book file via
         *     `get-book-file` when available, otherwise chapters materialize
         *     lazily), or none (`metadata_only`: a bare metadata entry — add
         *     the content later by attaching a file/plugin book to it). The
         *     metadata entry is created automatically (parsed from the file /
         *     the plugin's own entry), taken from a plugin catalog
         *     (`meta_plugin_source` + `meta_plugin_book_id`), attached to an
         *     existing entry (`book_id`), or described manually. The metadata
         *     source is independent of the content source: metadata may come
         *     from plugin A while the content comes from plugin B.
         *     `title`/`authors`/`description`/`cover_url`/`ext` override the
         *     produced metadata (never applied when attaching). When the
         *     plugin source declares >1 volumes, the acquisition auto-splits
         *     into one series + one book per 卷 (the response carries them all).
         *     The split is driven by the CONTENT source's own volume
         *     declaration; the content source must declare its volume structure
         *     (400 otherwise — an undeclared content source cannot be sliced
         *     per volume) and may declare FEWER volumes than the metadata
         *     source (metadata-only series entries, e.g. bangumi 系列, may list
         *     not-yet-published volumes; those become metadata-only books with
         *     no content). A content source declaring MORE volumes than the
         *     metadata series is refused (400).
         */
        post: operations["uploadBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Book metadata plus files visible to the caller */
        get: operations["getBook"];
        put?: never;
        post?: never;
        /**
         * Delete the metadata entry (creator or admin). Metadata and file
         *     deletion are distinct operations: deleting files never touches the
         *     metadata and deleting metadata only succeeds once every file has
         *     been deleted explicitly.
         */
        delete: operations["deleteBook"];
        options?: never;
        head?: never;
        /** Edit metadata (creator or admin) */
        patch: operations["patchBook"];
        trace?: never;
    };
    "/api/books/{id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve the stored cover image bytes (extracted from an uploaded
         *     epub). Unauthenticated on purpose: `<img>` elements cannot send
         *     the Authorization header, and book ids are unguessable uuids
         *     (same capability-like model as share tokens). Books without a
         *     stored cover answer 404 so callers fall back to a placeholder.
         */
        get: operations["getBookCover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update metadata from the book's recorded metadata source (creator
         *     or admin). Re-pulls title/authors/description/cover-url from that
         *     source only and refreshes each plugin file's chapter titles from
         *     its own content source; materialized chapter content is never
         *     overwritten. A book whose metadata came from plugin A but holds
         *     files from plugin B is refreshed without B ever overwriting A's
         *     metadata.
         */
        post: operations["refreshBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach another file (format/edition) to existing metadata */
        post: operations["attachFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List series visible to the caller: those created by the caller,
         *     and series owning at least one visible member file (admins see
         *     all). Each entry carries its member count.
         */
        get: operations["listSeries"];
        put?: never;
        /** Create a series (any logged-in user; the creator manages it) */
        post: operations["createSeries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Series detail: metadata plus member books in volume order (files
         *     filtered by visibility; entries without visible files still
         *     appear with an empty `files` list).
         */
        get: operations["getSeriesDetail"];
        put?: never;
        post?: never;
        /**
         * Delete a series (creator or admin). Member books are unassigned
         *     (their entries stay standalone); the series row is removed.
         */
        delete: operations["deleteSeries"];
        options?: never;
        head?: never;
        /** Edit series metadata (creator or admin) */
        patch: operations["patchSeries"];
        trace?: never;
    };
    "/api/series/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the member set + order of a series in one call: the
         *     listed books (in order) become volumes 1..N; former members not
         *     listed are unassigned. The caller must manage the series and
         *     every listed book.
         */
        put: operations["putSeriesMembers"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File detail with chapter titles and its book metadata */
        get: operations["getFile"];
        put?: never;
        post?: never;
        /** Delete a file (owner or admin) */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        /** Toggle visibility or rename the edition label (owner or admin) */
        patch: operations["patchFile"];
        trace?: never;
    };
    "/api/files/{id}/chapters/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one chapter's content */
        get: operations["getChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A localized chapter image (public, no auth)
         * @description Serves an illustration that plugin chapter text referenced; the
         *     host downloaded it at materialization time and rewrote the
         *     chapter HTML to this endpoint. `id` is the sha256 of the image
         *     bytes (unguessable, same capability-like model as book covers —
         *     `<img>` tags cannot send the Authorization header).
         */
        get: operations["getImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download the retained original file bytes */
        get: operations["downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/content-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebind a file's chapter source (owner/admin only; metadata/content
         *     separation). The target instance must exist; when it has the
         *     `lookup` capability the book must resolve via get-book. Existing
         *     chapter bodies are cleared and re-materialized from the new source
         *     on next read; title placeholders refresh from the new source.
         */
        post: operations["setContentSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/rematerialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear a plugin file's stored chapter bodies (owner/admin only) so
         *     they are lazily re-pulled from its content source on the next
         *     read. The retry path for degraded materializations — e.g. images
         *     that fell back to remote URLs because the download failed; the
         *     re-pull stores them via the plugin's store-image import.
         */
        post: operations["rematerializeFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every reading session of the caller, newest first
         * @description Progress of one user across all files, in a single request — the
         *     shelf and series pages derive per-book/per-volume progress from
         *     it (only sessions on files the caller may still view are usable
         *     by the client, which maps `file_id` through its book list).
         */
        get: operations["listAllSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user's reading sessions for a file */
        get: operations["listSessions"];
        put?: never;
        /** Create a session (reuses an existing one with the same label) */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update session progress (all fields optional; clamped) */
        put: operations["updateSession"];
        post?: never;
        /** Delete a session (owner or admin) */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a share link for a file or one of its sessions */
        post: operations["createShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public share info (no auth; session progress snapshot) */
        get: operations["getShare"];
        put?: never;
        post?: never;
        /** Delete a share (creator or admin) */
        delete: operations["deleteShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anonymous read: book, file and chapter titles */
        get: operations["shareBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}/chapters/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anonymous read: one chapter */
        get: operations["shareChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
            allow_register: boolean;
        };
        /** @enum {string} */
        Role: "admin" | "user";
        User: {
            id: string;
            username: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            created_at: string;
        };
        Credentials: {
            username: string;
            password: string;
        };
        AuthResponse: {
            /** @description JWT (send as `Authorization: Bearer <token>`) */
            token: string;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        Visibility: "private" | "public";
        BookMeta: {
            id: string;
            title: string;
            authors: string[];
            description: string | null;
            cover_url: string | null;
            ext: components["schemas"]["BookExt"];
            /** @description Id of the user who created this metadata entry */
            created_by: string | null;
            /** Format: date-time */
            created_at: string;
            /**
             * @description Series this book is a volume of (null = standalone). Volume
             *     splits assign every 卷 its own book entry plus one series
             *     row; manual assignment (`PATCH /api/books/{id}`) moves books
             *     in and out of series.
             */
            series_id: string | null;
            /** @description 1-based volume ordinal inside the series (0 = standalone) */
            volume_no: number;
        };
        /**
         * @description Extended book metadata (bangumi/douban-style). Every known key is
         *     optional; `null`/absent = unset. Unknown keys are preserved
         *     verbatim so future server fields round-trip through old clients.
         *     `isbn` is stored canonically as a hyphenless ISBN-13 (valid
         *     ISBN-10 inputs are converted); invalid ISBNs are rejected with
         *     400.
         */
        BookExt: {
            /** @description 副标题 */
            subtitle?: string | null;
            /** @description 原作名 */
            original_title?: string | null;
            /** @description Canonical hyphenless ISBN-13 */
            isbn?: string | null;
            /** @description 出版社 */
            publisher?: string | null;
            /** @description 出版时间 (stored exactly as supplied) */
            pub_date?: string | null;
            /** @description 译者 */
            translators?: string[] | null;
            /** @description 插画师 */
            illustrators?: string[] | null;
            /** @description 页数 */
            pages?: number | null;
            /** @description 定价 (currency as printed) */
            price?: string | null;
            /** @description 装帧 (文库/单行本/…) */
            binding?: string | null;
            /** @description BCP-47 language hint ("zh-CN", "ja") */
            language?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * @description Extended series metadata: edition-independent facts of the
         *     publication family. Same rules as `BookExt` (all optional,
         *     unknown keys preserved).
         */
        SeriesExt: {
            /** @description 原作名 */
            original_title?: string | null;
            /** @description 出版社 */
            publisher?: string | null;
            /** @description 首卷发售时间 (verbatim) */
            pub_date?: string | null;
            /** @description BCP-47 language hint */
            language?: string | null;
            /**
             * @description Publication status
             * @enum {string|null}
             */
            status?: "ongoing" | "completed" | "hiatus" | null;
            /** @description Planned volume count */
            total_volumes?: number | null;
            /** @description 类型标签 */
            tags?: string[] | null;
        } & {
            [key: string]: unknown;
        };
        FileMeta: {
            id: string;
            book_id: string;
            /** @description 'local' for uploads, otherwise the plugin id */
            source: string;
            /** @description Id within the source (same as `id` for local files) */
            external_id: string;
            /**
             * @description Instance id whose chapters back this file when different from
             *     `source` (metadata/content source separation); null = `source`.
             */
            content_source: string | null;
            /** @description Book id inside the content source; null = `external_id`. */
            content_external_id: string | null;
            /** @enum {string} */
            format: "epub" | "txt" | "plugin";
            /** @description Short human label for this edition */
            label: string;
            visibility: components["schemas"]["Visibility"];
            owner_id: string | null;
            chapter_count: number;
            /** Format: date-time */
            created_at: string;
            /**
             * @description Volume slice of the source book this file covers (0 = the
             *     whole book). A multi-volume plugin book is acquired as one
             *     file per 卷.
             */
            volume_no: number;
            /**
             * @description Flat chapter index of this volume's first chapter inside the
             *     source (persisted because the plugin is stateless); lazy
             *     chapter pulls use `volume_offset + idx`.
             */
            volume_offset: number;
            /**
             * @description Retained original file bytes (`data/files/`, served by
             *     `GET /api/files/{id}/download`). null = plugin chapter-mode
             *     files and uploads made before original retention.
             */
            original?: {
                /** @description File extension without the dot (epub / txt) */
                ext: string;
                size: number;
                sha256: string;
            } | null;
        };
        ChapterMeta: {
            idx: number;
            title: string;
        };
        /** @description One node of the hierarchical table of contents. `idx` is the chapter index this entry points to (`null` for pure group nodes); leaf entries reference entries of the `chapters` list. */
        TocNode: {
            title: string;
            idx: number | null;
            /** @description Id fragment of the source href (`file.html#section`) when this entry points into the middle of its chapter; the reader scrolls to the element with that id. */
            frag?: string | null;
            children: components["schemas"]["TocNode"][];
        };
        Chapter: {
            idx: number;
            title: string;
            /**
             * @description Sanitized HTML. Text/plugin chapters and legacy EPUB imports
             *     are fragments. Newly parsed EPUB chapters are full documents
             *     beginning with <!doctype html>, with passive publication CSS,
             *     SVG/MathML and rewritten local resources. Render full documents
             *     only in a sandboxed frame WITHOUT allow-scripts and with a CSP
             *     blocking network access except /api/images/, inline styles and
             *     embedded data images/fonts. Never insert publication CSS in the
             *     application DOM. html[data-epub-layout] retains the resolved OPF
             *     rendition layout (reflowable or pre-paginated).
             */
            content: string;
        };
        Position: {
            chapter_idx: number;
            in_chapter: {
                /** @description Scroll fraction within the chapter (web reader) */
                fraction: number;
            } | {
                /** @description Character offset within the chapter (non-web readers) */
                offset: number;
            };
        };
        /**
         * @description A series: metadata grouping for the volumes of one publication
         *     family (e.g. a light-novel series split from a multi-volume
         *     plugin source). Member books carry `series_id` + `volume_no`.
         */
        SeriesBrief: {
            id: string;
            title: string;
            authors: string[];
            description: string | null;
            cover_url: string | null;
            ext: components["schemas"]["SeriesExt"];
            /**
             * @description Publication status projected from `ext.status` (null = unset)
             * @enum {string|null}
             */
            status: "ongoing" | "completed" | "hiatus" | null;
            /** @description Number of member books (all visibilities) */
            volume_count: number;
            created_by: string | null;
            /** Format: date-time */
            created_at: string;
        };
        SeriesDetail: {
            series: components["schemas"]["SeriesBrief"];
            /** @description Member books in volume order, files filtered by visibility */
            books: components["schemas"]["BookDetail"][];
        };
        /**
         * @description Result of one acquisition (`POST /api/books`). When the plugin
         *     source declared >1 volumes, `series` is the created series and
         *     `books` holds one entry per 卷; otherwise `series` is null and
         *     `books` has exactly one entry. Always non-empty.
         */
        AcquireResult: {
            series: components["schemas"]["SeriesBrief"];
            books: components["schemas"]["BookDetail"][];
        };
        BookDetail: {
            book: components["schemas"]["BookMeta"];
            /** @description Files of this book visible to the caller (empty for a metadata-only entry) */
            files: components["schemas"]["FileMeta"][];
            series: components["schemas"]["SeriesBrief"];
        };
        BookListEntry: {
            book: components["schemas"]["BookMeta"];
            /** @description Files of this book visible to the caller */
            files: components["schemas"]["FileMeta"][];
            /** @description Series this book belongs to (null = standalone) */
            series: components["schemas"]["SeriesBrief"];
        };
        FileDetail: {
            file: components["schemas"]["FileMeta"];
            book: components["schemas"]["BookMeta"];
            chapters: components["schemas"]["ChapterMeta"][];
            toc: components["schemas"]["TocNode"][];
        };
        /** @description Metadata edit (creator or admin) plus optional series membership changes. `series_id`: a series id moves the book into it, explicit `null` unassigns, absent keeps the current series. `volume_no`: 1-based ordinal; absent/`null` = next free volume. Volume numbers within a series are unique (409 otherwise). */
        PatchBook: {
            title?: string;
            description?: string;
            series_id?: string | null;
            volume_no?: number | null;
            /** @description Extended-metadata merge patch (absent = keep, null = clear, value = set) */
            ext?: components["schemas"]["BookExt"];
        };
        PatchFile: {
            visibility?: components["schemas"]["Visibility"];
            label?: string;
        };
        ReadingSession: {
            id: string;
            user_id: string;
            file_id: string;
            label: string;
            position: components["schemas"]["Position"];
            /** Format: date-time */
            updated_at: string;
        };
        SessionsResponse: {
            file_id: string;
            sessions: components["schemas"]["ReadingSession"][];
        };
        CreateSession: {
            /** @description Defaults to "default" */
            label?: string;
        };
        UpdatePosition: {
            chapter_idx?: number;
            /** @description New chapter progress. Either a scroll fraction (`{fraction}`) or a character offset (`{offset}`) — the two channels are mutually exclusive. */
            in_chapter?: {
                fraction: number;
            } | {
                offset: number;
            };
        };
        /** @enum {string} */
        ShareKind: "book" | "session";
        CreateShare: {
            kind?: components["schemas"]["ShareKind"];
            /** @description Required when kind is "session" */
            session_id?: string;
            expires_days?: number;
        };
        ShareResponse: {
            token: string;
            /** @description Frontend path of the share page */
            url: string;
            kind: components["schemas"]["ShareKind"];
            file_id: string;
            session_id: string | null;
            expires_at: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ShareBookView: {
            id: string;
            title: string;
            authors: string[];
            description: string | null;
        };
        ShareFileView: {
            id: string;
            /** @enum {string} */
            format: "epub" | "txt" | "plugin";
            label: string;
            chapter_count: number;
        };
        ShareSessionView: {
            id: string;
            label: string;
            owner_username: string;
            position: components["schemas"]["Position"];
            /** @description Progress within the current chapter, 0..100 */
            percent: number;
            /** Format: date-time */
            updated_at: string;
        };
        ShareView: {
            kind: components["schemas"]["ShareKind"];
            book: components["schemas"]["ShareBookView"];
            file: components["schemas"]["ShareFileView"];
            /** @description Present when kind is "session" */
            session: components["schemas"]["ShareSessionView"] | null;
            /** Format: date-time */
            created_at: string;
            expires_at: string | null;
        };
        ShareBookResponse: {
            book: components["schemas"]["ShareBookView"];
            file: components["schemas"]["ShareFileView"];
            chapters: components["schemas"]["ChapterMeta"][];
            toc: components["schemas"]["TocNode"][];
        };
        /** @description One registered plugin instance (source id = `id`) */
        PluginInstance: {
            /** @description Source id used in `book_files.source` */
            id: string;
            /** @description Basename of the wasm component backing this instance */
            wasm_file: string;
            /** @description Human-readable plugin name (from the plugin itself) */
            name: string;
            enabled: boolean;
            /** @description Subset of [declare, search, lookup, identify, content, book-file]. book-file instances materialize whole book files through the upload parser (file mode wins over chapter mode). */
            capabilities: string[];
            /**
             * @description Interaction hints declared by the plugin (`source-info` export):
             *     how the frontend should present this source when acquiring
             *     books. `kind` = "search" | "manual-id" | "browse" | ""
             *     (empty = derive from capabilities).
             */
            source_info: {
                kind: string;
                id_kind: string;
                id_hint?: string | null;
                search_hint?: string | null;
            };
        };
        /** @description One field of a plugin's configuration schema */
        ConfigField: {
            key: string;
            /** @description zh-CN display label for the admin form */
            label: string;
            /** @enum {string} */
            kind: "string" | "number" | "boolean" | "enum" | "list-of-string";
            /** @description Enum options (kind=enum); index is the stored value */
            options?: string[];
            /** @description Serialized default value (JSON) */
            default?: string | null;
            required: boolean;
            hint?: string | null;
        };
        /** @description Plugin config schema plus the stored values, for the admin form */
        ConfigSchema: {
            fields: components["schemas"]["ConfigField"][];
            /** @description Current validated values keyed by field key */
            config: Record<string, never>;
        };
        ConfigError: {
            field: string;
            message: string;
        };
        /** @description One search hit, annotated with the library book it is already synced into */
        PluginSearchItem: {
            /** @description Book id inside the source */
            id: string;
            title: string;
            authors: string[];
            description?: string | null;
            cover_url?: string | null;
            /** @description Library metadata entry already materialized for this book, if any */
            book_id: string | null;
        };
        PluginSearchResponse: {
            /** @description Source-side total match count (may be capped by the source) */
            total: number;
            items: components["schemas"]["PluginSearchItem"][];
        };
    };
    responses: {
        /** @description Structured config validation errors (field-by-field for inline form display) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                    errors: components["schemas"]["ConfigError"][];
                };
            };
        };
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not allowed to perform this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist (or share expired) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Book (metadata) id */
        BookId: string;
        /** @description Book file id */
        FileId: string;
        /** @description Series id */
        SeriesId: string;
        /** @description Share token */
        ShareToken: string;
        /** @description Plugin instance id (source id) */
        PluginId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Registered, token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Registration is disabled */
            403: components["responses"]["Error"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Logged in, token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookie cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered instances in creation order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInstance"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    wasmFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wasm file basenames, e.g. ["wiki.wasm", "reader.wasm"] */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    syncPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Number of books (re-)synced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        synced: number;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    registerInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Explicit instance id (default: generated uuid) */
                    id?: string;
                    wasm_file: string;
                    /** @description Config values keyed by schema field keys */
                    config?: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description The registered instance */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInstance"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Files still reference the instance (delete them first) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        files: string[];
                    };
                };
            };
        };
    };
    setInstanceEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description The updated instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInstance"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    syncInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Number of books (re-)synced for the instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        synced: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    pluginConfigSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema fields and the stored (validated) config values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSchema"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putPluginConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Config values keyed by schema field keys */
                    config: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description The updated instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInstance"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    searchPlugins: {
        parameters: {
            query?: {
                /** @description Free-text query (empty = page through everything) */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search page, entries annotated with their library book id when already materialized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginSearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listBooks: {
        parameters: {
            query?: {
                /** @description Substring match on book title */
                q?: string;
                /** @description Filter by file source ('local' or a plugin id) */
                source?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata entries with at least one visible file, plus metadata-only entries (no files yet) the caller owns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookListEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Epub or txt file — the content. Mutually exclusive
                     *     with `plugin_source` + `plugin_book_id` (plugin
                     *     content) and with `metadata_only`: exactly one content
                     *     source is used. When given together with
                     *     `plugin_source`, the file is the content and the
                     *     plugin only supplies the metadata.
                     */
                    file?: string;
                    /**
                     * @description Create a bare metadata entry without any content
                     *     (no file is created). `meta_plugin_source` +
                     *     `meta_plugin_book_id` name the metadata source
                     *     (catalog entry), or `title`/`authors`/… describe the
                     *     entry manually (a title is required). Content may be
                     *     attached later via `POST /api/books/{id}/files`.
                     * @default false
                     */
                    metadata_only?: boolean;
                    /**
                     * @description Choose whether this file is published
                     * @default private
                     * @enum {string}
                     */
                    visibility?: "private" | "public";
                    /** @description Short human label for this edition (e.g. "proofread") */
                    label?: string;
                    /**
                     * @description Attach the content to this existing metadata entry
                     *     instead of creating one. The caller must be able to
                     *     see the book. Mutually exclusive with the plugin
                     *     metadata modes (a plugin book attached this way must
                     *     not already be materialized under another entry).
                     */
                    book_id?: string;
                    /**
                     * @description Together with `plugin_book_id`: the *content* comes
                     *     from this plugin source's book (materialized into the
                     *     library; whole-book files via `get-book-file`, else
                     *     lazy chapter mode). When no `file`,
                     *     `meta_plugin_source`, or `book_id` is given, the
                     *     plugin's own entry also provides the metadata.
                     */
                    plugin_source?: string;
                    /** @description Id of the book inside the plugin's catalog */
                    plugin_book_id?: string;
                    /**
                     * @description Together with `meta_plugin_book_id`: the metadata
                     *     comes from this plugin source's catalog — possibly a
                     *     different plugin than the content source. Overrides
                     *     (`title`/…) apply on top of its entry.
                     */
                    meta_plugin_source?: string;
                    /** @description Id of the metadata book inside its plugin's catalog */
                    meta_plugin_book_id?: string;
                    /** @description Manual metadata: overrides the title (auto mode uses the parsed/identified one) */
                    title?: string;
                    /** @description Manual metadata: JSON string array, e.g. `["A","B"]` */
                    authors?: string;
                    /** @description Manual metadata: overrides the description */
                    description?: string;
                    /** @description Manual metadata: cover image URL */
                    cover_url?: string;
                    /**
                     * @description Manual metadata: extended fields as a JSON object
                     *     (see `BookExt`), e.g.
                     *     `{"isbn":"9787536692930","publisher":"出版社"}`.
                     *     Overrides the parsed/identified value per-key.
                     */
                    ext?: string;
                };
            };
        };
        responses: {
            /**
             * @description The created series (when a multi-volume source book was
             *     split) and the created books, each with its first file
             *     (empty files array for a metadata-only addition).
             */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcquireResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Book still has files; delete them first */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        /** @description Ids of the files still attached to the book */
                        files: string[];
                    };
                };
            };
        };
    };
    patchBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBook"];
            };
        };
        responses: {
            /** @description Updated metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookMeta"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getBookCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cover image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    refreshBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata refreshed from the plugin source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookMeta"];
                };
            };
            /** @description Book has no plugin source (or the source is not loaded) */
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    attachFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /**
                     * @description Defaults to the most visible existing file of the book
                     *     (private if the book has no visible files yet)
                     * @enum {string}
                     */
                    visibility?: "private" | "public";
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Attached file */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSeries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesBrief"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSeries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title: string;
                    authors?: string[];
                    description?: string;
                    ext?: components["schemas"]["SeriesExt"];
                };
            };
        };
        responses: {
            /** @description Created series */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesBrief"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getSeriesDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: components["parameters"]["SeriesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Series detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: components["parameters"]["SeriesId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchSeries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: components["parameters"]["SeriesId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    authors?: string[];
                    description?: string;
                    /** @description Extended-metadata merge patch (absent = keep, null = clear, value = set) */
                    ext?: components["schemas"]["SeriesExt"];
                };
            };
        };
        responses: {
            /** @description Updated series */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesBrief"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    putSeriesMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Series id */
                id: components["parameters"]["SeriesId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    book_ids: string[];
                };
            };
        };
        responses: {
            /** @description Updated series detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File detail (plugin chapter titles materialized lazily) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchFile"];
            };
        };
        responses: {
            /** @description Updated file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
                /** @description Zero-based chapter index */
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            /** @description Unknown image id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The original bytes (epub or txt) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/epub+zip": string;
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No original retained for this file */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setContentSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Target plugin instance id (must exist) */
                    content_source: string;
                    /** @description Book id inside the content source (default: the file's external_id) */
                    content_external_id?: string;
                };
            };
        };
        responses: {
            /** @description The updated file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    rematerializeFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The updated file (bodies cleared) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAllSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the caller, ordered by `updated_at` desc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSession"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the caller for this file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSession"];
            };
        };
        responses: {
            /** @description Created (or the existing session with that label) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePosition"];
            };
        };
        responses: {
            /** @description Updated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSession"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShare"];
            };
        };
        responses: {
            /** @description Share link created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareView"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    shareBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book + file + chapter titles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareBookResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    shareChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
