/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health and capabilities */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in, receive a JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List loaded wasm plugin sources */
        get: operations["listPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-sync all plugin catalogs into the library (admin only) */
        post: operations["syncPlugins"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible books with their visible files */
        get: operations["listBooks"];
        put?: never;
        /** Upload a book — creates a metadata entry plus its first file */
        post: operations["uploadBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Book metadata plus files visible to the caller */
        get: operations["getBook"];
        put?: never;
        post?: never;
        /** Delete metadata and all its files (creator or admin) */
        delete: operations["deleteBook"];
        options?: never;
        head?: never;
        /** Edit metadata (creator or admin) */
        patch: operations["patchBook"];
        trace?: never;
    };
    "/api/books/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach another file (format/edition) to existing metadata */
        post: operations["attachFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File detail with chapter titles and its book metadata */
        get: operations["getFile"];
        put?: never;
        post?: never;
        /** Delete a file (owner or admin) */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        /** Toggle visibility or rename the edition label (owner or admin) */
        patch: operations["patchFile"];
        trace?: never;
    };
    "/api/files/{id}/chapters/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one chapter's content */
        get: operations["getChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user's reading sessions for a file */
        get: operations["listSessions"];
        put?: never;
        /** Create a session (reuses an existing one with the same label) */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update session progress (all fields optional; clamped) */
        put: operations["updateSession"];
        post?: never;
        /** Delete a session (owner or admin) */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a share link for a file or one of its sessions */
        post: operations["createShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public share info (no auth; session progress snapshot) */
        get: operations["getShare"];
        put?: never;
        post?: never;
        /** Delete a share (creator or admin) */
        delete: operations["deleteShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anonymous read: book, file and chapter titles */
        get: operations["shareBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}/chapters/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anonymous read: one chapter */
        get: operations["shareChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
            /** @description false = single-user local mode */
            auth_enabled: boolean;
            allow_register: boolean;
        };
        /** @enum {string} */
        Role: "admin" | "user";
        User: {
            id: string;
            username: string;
            role: components["schemas"]["Role"];
            created_at: string;
        };
        Credentials: {
            username: string;
            password: string;
        };
        AuthResponse: {
            /** @description JWT (send as `Authorization: Bearer <token>`) */
            token: string;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        Visibility: "private" | "public";
        BookMeta: {
            id: string;
            title: string;
            authors: string[];
            description: string | null;
            cover_url: string | null;
            /** @description Id of the user who created this metadata entry */
            created_by: string | null;
            created_at: string;
        };
        FileMeta: {
            id: string;
            book_id: string;
            /** @description 'local' for uploads, otherwise the plugin id */
            source: string;
            /** @description Id within the source (same as `id` for local files) */
            external_id: string;
            /** @enum {string} */
            format: "epub" | "txt" | "plugin";
            /** @description Short human label for this edition */
            label: string;
            visibility: components["schemas"]["Visibility"];
            owner_id: string | null;
            chapter_count: number;
            created_at: string;
        };
        ChapterMeta: {
            idx: number;
            title: string;
        };
        Chapter: {
            idx: number;
            title: string;
            /**
             * @description `html`: sanitized HTML fragment (epub chapters, structure preserved, images inlined as data URIs). `text`: plain text (txt uploads, plugin chapters).
             * @enum {string}
             */
            format: "html" | "text";
            /** @description Chapter content per `format`. */
            content: string;
        };
        Position: {
            chapter_idx: number;
            /** @description Character offset within the chapter (non-web readers) */
            offset: number;
            /** @description Scroll fraction within the chapter (web reader) */
            fraction: number;
        };
        BookDetail: {
            book: components["schemas"]["BookMeta"];
            files: components["schemas"]["FileMeta"][];
        };
        BookListEntry: {
            book: components["schemas"]["BookMeta"];
            /** @description Files of this book visible to the caller */
            files: components["schemas"]["FileMeta"][];
        };
        FileDetail: {
            file: components["schemas"]["FileMeta"];
            book: components["schemas"]["BookMeta"];
            chapters: components["schemas"]["ChapterMeta"][];
        };
        PatchBook: {
            title?: string;
            description?: string;
        };
        PatchFile: {
            visibility?: components["schemas"]["Visibility"];
            label?: string;
        };
        ReadingSession: {
            id: string;
            user_id: string;
            file_id: string;
            label: string;
            position: components["schemas"]["Position"];
            updated_at: string;
        };
        SessionsResponse: {
            file_id: string;
            book_title: string;
            sessions: components["schemas"]["ReadingSession"][];
        };
        CreateSession: {
            /** @description Defaults to "default" */
            label?: string;
        };
        UpdatePosition: {
            chapter_idx?: number;
            offset?: number;
            fraction?: number;
        };
        /** @enum {string} */
        ShareKind: "book" | "session";
        CreateShare: {
            kind: components["schemas"]["ShareKind"];
            /** @description Required when kind is "session" */
            session_id?: string;
            expires_days?: number;
        };
        ShareResponse: {
            token: string;
            /** @description Frontend path of the share page */
            url: string;
            kind: components["schemas"]["ShareKind"];
            /** @enum {string} */
            mode: "read" | "progress";
            file_id: string;
            session_id: string | null;
            expires_at: string | null;
            created_at: string;
        };
        ShareBookView: {
            id: string;
            title: string;
            authors: string[];
            description: string | null;
        };
        ShareFileView: {
            id: string;
            format: string;
            label: string;
            chapter_count: number;
        };
        ShareSessionView: {
            id: string;
            label: string;
            owner_username: string;
            position: components["schemas"]["Position"];
            /** @description Progress within the current chapter, 0..100 */
            percent: number;
            updated_at: string;
        };
        ShareView: {
            kind: components["schemas"]["ShareKind"];
            /** @enum {string} */
            mode: "read" | "progress";
            book: components["schemas"]["ShareBookView"];
            file: components["schemas"]["ShareFileView"];
            /** @description Present when kind is "session" */
            session: components["schemas"]["ShareSessionView"] | null;
            created_at: string;
            expires_at: string | null;
        };
        ShareBookResponse: {
            book: components["schemas"]["ShareBookView"];
            file: components["schemas"]["ShareFileView"];
            chapters: components["schemas"]["ChapterMeta"][];
        };
        PluginInfo: {
            id: string;
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not allowed to perform this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist (or share expired) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Book (metadata) id */
        BookId: string;
        /** @description Book file id */
        FileId: string;
        /** @description Share token */
        ShareToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Registered, token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Registration is disabled */
            403: components["responses"]["Error"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Logged in, token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loaded plugin ids */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInfo"][];
                };
            };
        };
    };
    syncPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Number of books (re-)synced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        synced: number;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listBooks: {
        parameters: {
            query?: {
                /** @description Substring match on book title */
                q?: string;
                /** @description Filter by file source ('local' or a plugin id) */
                source?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata entries that own at least one visible file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookListEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Epub or txt file
                     */
                    file: string;
                    /**
                     * @description Choose whether this upload is published
                     * @default private
                     * @enum {string}
                     */
                    visibility?: "private" | "public";
                    /** @description Short human label for this edition (e.g. "proofread") */
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Book and its first file created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBook"];
            };
        };
        responses: {
            /** @description Updated metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookMeta"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    attachFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /**
                     * @description Defaults to the most visible existing file of the book
                     *     (private if the book has no visible files yet)
                     * @enum {string}
                     */
                    visibility?: "private" | "public";
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Attached file */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File detail (plugin chapter titles materialized lazily) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchFile"];
            };
        };
        responses: {
            /** @description Updated file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
                /** @description Zero-based chapter index */
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the caller for this file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSession"];
            };
        };
        responses: {
            /** @description Created (or the existing session with that label) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePosition"];
            };
        };
        responses: {
            /** @description Updated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSession"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShare"];
            };
        };
        responses: {
            /** @description Share link created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareView"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    shareBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book + file + chapter titles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareBookResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    shareChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
