/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health and capabilities */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in, receive a JWT */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered plugin instances (id, wasm file, name, capabilities) */
        get: operations["listPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/wasm-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Basenames of the compiled wasm components loaded at startup (admin only) */
        get: operations["wasmFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-sync the catalogs of every enabled declare-capable instance (admin only) */
        post: operations["syncPlugins"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a plugin instance (admin only). `wasm_file` must be a
         *     basename returned by GET /api/plugins/wasm-files; `config` is
         *     validated against the plugin's config schema (defaults fill the
         *     rest). An explicit `id` becomes the source id used in
         *     `book_files.source` — stable ids let metadata plugins point their
         *     `content-source` at a content plugin's instance. A declare-capable
         *     instance is synced right away.
         */
        post: operations["registerInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a plugin instance (admin only) */
        delete: operations["deleteInstance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/instances/{id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Enable or disable a plugin instance (admin only). Disabling stops
         *     sync/browse/materialize; already materialized chapters stay
         *     readable.
         */
        put: operations["setInstanceEnabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/config-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config schema plus current values for the admin form (admin only) */
        get: operations["pluginConfigSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Validate and store an instance's configuration (admin only).
         *     Unknown keys are rejected, required fields enforced, enum indices
         *     range-checked; errors come back field-by-field for inline form
         *     display. A declare-capable instance is re-synced after the change.
         */
        put: operations["putPluginConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated catalog search of a search-capable instance. The library
         *     does not enumerate large sources; users pick books here and
         *     materialize them one by one. Caps: limit 1..50, offset <= 10000.
         */
        get: operations["searchPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Materialize exactly one book of a lookup-capable source into the
         *     library. Materialization modes (docs/plugin-http-api-design.md): a
         *     source declaring book-file is materialized in FILE mode first —
         *     the whole file is fetched via get-book-file and parsed like an
         *     upload (format epub/txt, chapters, hierarchical TOC, sanitized
         *     HTML); otherwise CHAPTER mode: metadata + virtual file +
         *     chapter-title placeholders, chapter bodies stay lazy until first
         *     read. The caller claims the metadata (becomes its creator).
         */
        post: operations["materializeBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible books with their visible files */
        get: operations["listBooks"];
        put?: never;
        /**
         * Upload a book — one endpoint for all three metadata modes:
         *     attach to existing metadata (`book_id`), metadata from a plugin
         *     source (`plugin_source` + `plugin_book_id`), or auto (plugins are
         *     asked to identify the file, falling back to parsing the file).
         *     `title`/`authors`/`description`/`cover_url` override the produced
         *     metadata (manual mode; never applied when attaching).
         */
        post: operations["uploadBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Book metadata plus files visible to the caller */
        get: operations["getBook"];
        put?: never;
        post?: never;
        /**
         * Delete the metadata entry (creator or admin). Metadata and file
         *     deletion are distinct operations: deleting files never touches the
         *     metadata and deleting metadata only succeeds once every file has
         *     been deleted explicitly.
         */
        delete: operations["deleteBook"];
        options?: never;
        head?: never;
        /** Edit metadata (creator or admin) */
        patch: operations["patchBook"];
        trace?: never;
    };
    "/api/books/{id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve the stored cover image bytes (extracted from an uploaded
         *     epub). Unauthenticated on purpose: `<img>` elements cannot send
         *     the Authorization header, and book ids are unguessable uuids
         *     (same capability-like model as share tokens). Books without a
         *     stored cover answer 404 so callers fall back to a placeholder.
         */
        get: operations["getBookCover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update metadata from the book's plugin source(s) (creator or
         *     admin). Re-pulls title/authors/description/cover-url and refreshes
         *     the plugin file's chapter titles; materialized chapter content is
         *     never overwritten.
         */
        post: operations["refreshBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach another file (format/edition) to existing metadata */
        post: operations["attachFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** File detail with chapter titles and its book metadata */
        get: operations["getFile"];
        put?: never;
        post?: never;
        /** Delete a file (owner or admin) */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        /** Toggle visibility or rename the edition label (owner or admin) */
        patch: operations["patchFile"];
        trace?: never;
    };
    "/api/files/{id}/chapters/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one chapter's content */
        get: operations["getChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/content-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rebind a file's chapter source (owner/admin only; metadata/content
         *     separation). The target instance must exist; when it has the
         *     `lookup` capability the book must resolve via get-book. Existing
         *     chapter bodies are cleared and re-materialized from the new source
         *     on next read; title placeholders refresh from the new source.
         */
        post: operations["setContentSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user's reading sessions for a file */
        get: operations["listSessions"];
        put?: never;
        /** Create a session (reuses an existing one with the same label) */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update session progress (all fields optional; clamped) */
        put: operations["updateSession"];
        post?: never;
        /** Delete a session (owner or admin) */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a share link for a file or one of its sessions */
        post: operations["createShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public share info (no auth; session progress snapshot) */
        get: operations["getShare"];
        put?: never;
        post?: never;
        /** Delete a share (creator or admin) */
        delete: operations["deleteShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anonymous read: book, file and chapter titles */
        get: operations["shareBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{token}/chapters/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anonymous read: one chapter */
        get: operations["shareChapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
            /** @description false = single-user local mode */
            auth_enabled: boolean;
            allow_register: boolean;
        };
        /** @enum {string} */
        Role: "admin" | "user";
        User: {
            id: string;
            username: string;
            role: components["schemas"]["Role"];
            created_at: string;
        };
        Credentials: {
            username: string;
            password: string;
        };
        AuthResponse: {
            /** @description JWT (send as `Authorization: Bearer <token>`) */
            token: string;
            user: components["schemas"]["User"];
        };
        /** @enum {string} */
        Visibility: "private" | "public";
        BookMeta: {
            id: string;
            title: string;
            authors: string[];
            description: string | null;
            cover_url: string | null;
            /** @description Id of the user who created this metadata entry */
            created_by: string | null;
            created_at: string;
        };
        FileMeta: {
            id: string;
            book_id: string;
            /** @description 'local' for uploads, otherwise the plugin id */
            source: string;
            /** @description Id within the source (same as `id` for local files) */
            external_id: string;
            /**
             * @description Instance id whose chapters back this file when different from
             *     `source` (metadata/content source separation); null = `source`.
             */
            content_source: string | null;
            /** @description Book id inside the content source; null = `external_id`. */
            content_external_id: string | null;
            /** @enum {string} */
            format: "epub" | "txt" | "plugin";
            /** @description Short human label for this edition */
            label: string;
            visibility: components["schemas"]["Visibility"];
            owner_id: string | null;
            chapter_count: number;
            created_at: string;
        };
        ChapterMeta: {
            idx: number;
            title: string;
        };
        /** @description One node of the hierarchical table of contents. `idx` is the chapter index this entry points to (`null` for pure group nodes); leaf entries reference entries of the `chapters` list. */
        TocNode: {
            title: string;
            idx: number | null;
            /** @description Id fragment of the source href (`file.html#section`) when this entry points into the middle of its chapter; the reader scrolls to the element with that id. */
            frag?: string | null;
            children: components["schemas"]["TocNode"][];
        };
        Chapter: {
            idx: number;
            title: string;
            /**
             * @description `html`: sanitized HTML fragment (epub chapters, structure preserved, images inlined as data URIs). `text`: plain text (txt uploads, plugin chapters).
             * @enum {string}
             */
            format: "html" | "text";
            /** @description Chapter content per `format`. */
            content: string;
        };
        Position: {
            chapter_idx: number;
            /** @description Character offset within the chapter (non-web readers) */
            offset: number;
            /** @description Scroll fraction within the chapter (web reader) */
            fraction: number;
        };
        BookDetail: {
            book: components["schemas"]["BookMeta"];
            files: components["schemas"]["FileMeta"][];
        };
        BookListEntry: {
            book: components["schemas"]["BookMeta"];
            /** @description Files of this book visible to the caller */
            files: components["schemas"]["FileMeta"][];
        };
        FileDetail: {
            file: components["schemas"]["FileMeta"];
            book: components["schemas"]["BookMeta"];
            chapters: components["schemas"]["ChapterMeta"][];
            toc: components["schemas"]["TocNode"][];
        };
        PatchBook: {
            title?: string;
            description?: string;
        };
        PatchFile: {
            visibility?: components["schemas"]["Visibility"];
            label?: string;
        };
        ReadingSession: {
            id: string;
            user_id: string;
            file_id: string;
            label: string;
            position: components["schemas"]["Position"];
            updated_at: string;
        };
        SessionsResponse: {
            file_id: string;
            book_title: string;
            sessions: components["schemas"]["ReadingSession"][];
        };
        CreateSession: {
            /** @description Defaults to "default" */
            label?: string;
        };
        UpdatePosition: {
            chapter_idx?: number;
            offset?: number;
            fraction?: number;
        };
        /** @enum {string} */
        ShareKind: "book" | "session";
        CreateShare: {
            kind: components["schemas"]["ShareKind"];
            /** @description Required when kind is "session" */
            session_id?: string;
            expires_days?: number;
        };
        ShareResponse: {
            token: string;
            /** @description Frontend path of the share page */
            url: string;
            kind: components["schemas"]["ShareKind"];
            /** @enum {string} */
            mode: "read" | "progress";
            file_id: string;
            session_id: string | null;
            expires_at: string | null;
            created_at: string;
        };
        ShareBookView: {
            id: string;
            title: string;
            authors: string[];
            description: string | null;
        };
        ShareFileView: {
            id: string;
            format: string;
            label: string;
            chapter_count: number;
        };
        ShareSessionView: {
            id: string;
            label: string;
            owner_username: string;
            position: components["schemas"]["Position"];
            /** @description Progress within the current chapter, 0..100 */
            percent: number;
            updated_at: string;
        };
        ShareView: {
            kind: components["schemas"]["ShareKind"];
            /** @enum {string} */
            mode: "read" | "progress";
            book: components["schemas"]["ShareBookView"];
            file: components["schemas"]["ShareFileView"];
            /** @description Present when kind is "session" */
            session: components["schemas"]["ShareSessionView"] | null;
            created_at: string;
            expires_at: string | null;
        };
        ShareBookResponse: {
            book: components["schemas"]["ShareBookView"];
            file: components["schemas"]["ShareFileView"];
            chapters: components["schemas"]["ChapterMeta"][];
            toc: components["schemas"]["TocNode"][];
        };
        /** @description One registered plugin instance (source id = `id`) */
        PluginInstance: {
            /** @description Source id used in `book_files.source` */
            id: string;
            /** @description Basename of the wasm component backing this instance */
            wasm_file: string;
            /** @description Human-readable plugin name (from the plugin itself) */
            name: string;
            enabled: boolean;
            /** @description Subset of [declare, search, lookup, identify, content, book-file]. book-file instances materialize whole book files through the upload parser (file mode wins over chapter mode). */
            capabilities: string[];
        };
        /** @description One field of a plugin's configuration schema */
        ConfigField: {
            key: string;
            /** @description zh-CN display label for the admin form */
            label: string;
            /** @enum {string} */
            kind: "string" | "number" | "boolean" | "enum" | "list-of-string";
            /** @description Enum options (kind=enum); index is the stored value */
            options?: string[];
            /** @description Serialized default value (JSON) */
            default?: string | null;
            required: boolean;
            hint?: string | null;
        };
        /** @description Plugin config schema plus the stored values, for the admin form */
        ConfigSchema: {
            fields: components["schemas"]["ConfigField"][];
            /** @description Current validated values keyed by field key */
            config: Record<string, never>;
        };
        ConfigError: {
            field: string;
            message: string;
        };
        /** @description One search hit, annotated with the library book it is already synced into */
        PluginSearchItem: {
            /** @description Book id inside the source */
            id: string;
            title: string;
            authors: string[];
            description?: string | null;
            cover_url?: string | null;
            /** @description Library metadata entry already materialized for this book, if any */
            book_id: string | null;
        };
        PluginSearchResponse: {
            /** @description Source-side total match count (may be capped by the source) */
            total: number;
            items: components["schemas"]["PluginSearchItem"][];
        };
    };
    responses: {
        /** @description Structured config validation errors (field-by-field for inline form display) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                    errors: components["schemas"]["ConfigError"][];
                };
            };
        };
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not allowed to perform this action */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist (or share expired) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Book (metadata) id */
        BookId: string;
        /** @description Book file id */
        FileId: string;
        /** @description Share token */
        ShareToken: string;
        /** @description Plugin instance id (source id) */
        PluginId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Registered, token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Registration is disabled */
            403: components["responses"]["Error"];
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Logged in, token issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered instances in creation order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInstance"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    wasmFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wasm file basenames, e.g. ["wiki.wasm", "reader.wasm"] */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    syncPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Number of books (re-)synced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        synced: number;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    registerInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Explicit instance id (default: generated uuid) */
                    id?: string;
                    wasm_file: string;
                    /** @description Config values keyed by schema field keys */
                    config?: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description The registered instance */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInstance"];
                };
            };
            400: components["responses"]["ValidationError"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            /** @description Files still reference the instance (delete them first) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        files: string[];
                    };
                };
            };
        };
    };
    setInstanceEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description The updated instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInstance"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    pluginConfigSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema fields and the stored (validated) config values */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSchema"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putPluginConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Config values keyed by schema field keys */
                    config: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description The updated instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginInstance"];
                };
            };
            400: components["responses"]["ValidationError"];
            404: components["responses"]["NotFound"];
        };
    };
    searchPlugins: {
        parameters: {
            query?: {
                /** @description Free-text query (empty = page through everything) */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search page, entries annotated with their library book id when already materialized */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginSearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    materializeBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin instance id (source id) */
                id: components["parameters"]["PluginId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Book id inside the source */
                    book_id: string;
                };
            };
        };
        responses: {
            /** @description The materialized book with its visible files */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listBooks: {
        parameters: {
            query?: {
                /** @description Substring match on book title */
                q?: string;
                /** @description Filter by file source ('local' or a plugin id) */
                source?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata entries that own at least one visible file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookListEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description Epub or txt file
                     */
                    file: string;
                    /**
                     * @description Choose whether this upload is published
                     * @default private
                     * @enum {string}
                     */
                    visibility?: "private" | "public";
                    /** @description Short human label for this edition (e.g. "proofread") */
                    label?: string;
                    /**
                     * @description Attach the file to this existing metadata entry instead
                     *     of creating one. The caller must be able to see the
                     *     book. Mutually exclusive with `plugin_source`.
                     */
                    book_id?: string;
                    /**
                     * @description Take the metadata from this plugin source's catalog
                     *     (requires `plugin_book_id` too). The plugin book is
                     *     synced into the library if needed and the upload is
                     *     attached to its metadata entry.
                     */
                    plugin_source?: string;
                    /** @description Id of the book inside the plugin's catalog */
                    plugin_book_id?: string;
                    /** @description Manual metadata: overrides the title (auto mode uses the parsed/identified one) */
                    title?: string;
                    /** @description Manual metadata: JSON string array, e.g. `["A","B"]` */
                    authors?: string;
                    /** @description Manual metadata: overrides the description */
                    description?: string;
                    /** @description Manual metadata: cover image URL */
                    cover_url?: string;
                };
            };
        };
        responses: {
            /** @description Book and its first file created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Book still has files; delete them first */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        /** @description Ids of the files still attached to the book */
                        files: string[];
                    };
                };
            };
        };
    };
    patchBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchBook"];
            };
        };
        responses: {
            /** @description Updated metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookMeta"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getBookCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cover image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    refreshBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata refreshed from the plugin source */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookMeta"];
                };
            };
            /** @description Book has no plugin source (or the source is not loaded) */
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    attachFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book (metadata) id */
                id: components["parameters"]["BookId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /**
                     * @description Defaults to the most visible existing file of the book
                     *     (private if the book has no visible files yet)
                     * @enum {string}
                     */
                    visibility?: "private" | "public";
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Attached file */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File detail (plugin chapter titles materialized lazily) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchFile"];
            };
        };
        responses: {
            /** @description Updated file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
                /** @description Zero-based chapter index */
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    setContentSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Target plugin instance id (must exist) */
                    content_source: string;
                    /** @description Book id inside the content source (default: the file's external_id) */
                    content_external_id?: string;
                };
            };
        };
        responses: {
            /** @description The updated file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions of the caller for this file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSession"];
            };
        };
        responses: {
            /** @description Created (or the existing session with that label) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePosition"];
            };
        };
        responses: {
            /** @description Updated session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadingSession"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book file id */
                id: components["parameters"]["FileId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShare"];
            };
        };
        responses: {
            /** @description Share link created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareView"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    shareBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Book + file + chapter titles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareBookResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    shareChapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Share token */
                token: components["parameters"]["ShareToken"];
                idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chapter content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chapter"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
